---
dependencies:
  - preconfig

galaxy_info:
  author: Ivan Lugovoy
  description: >
    Эта роль предназначена для настройки и обслуживания веб-сервера Nginx в контейнере Docker.
  license: MIT
  min_ansible_version: 2.9
