---
nginx_user: nginx
nginx_worker_processes: auto
nginx_error_log: /var/log/nginx/error.log
nginx_error_log_level: notice
nginx_pid_file: /var/run/nginx.pid
nginx_worker_connections: 1024
nginx_log_format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'
nginx_access_log: /var/log/nginx/access.log
nginx_keepalive_timeout: 65
nginx_listen_port: 80
nginx_server_name: localhost
nginx_document_root: /var/www/html
nginx_index_files: index.php index.html index.htm
nginx_php_socket: web:9000