---
- name: preconfig - Создать домашнюю директорию проекта
  file:
    path: "/home/{{ ansible_user }}/php_app"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: preconfig - Установка Nginx, PHP и необходимых модулей
  apt:
    name:
      - nginx
      - php
      - php-fpm
      - php-mysql
      - python3-docker
    state: present
    update_cache: true

- name: preconfig - Установка необходимых пакетов для работы с Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - rsync
    state: present

- name: preconfig - Добавление GPG ключа официального репозитория Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: preconfig - Добавление репозитория Docker
  apt_repository:
    # yamllint disable-line rule:line-length
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: preconfig - Установка необходимых пакетов Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: preconfig - Проверяем запущен ли докер
  service:
    name: docker
    state: started
    enabled: true

- name: preconfig - Проверяем наличие группы docker
  ansible.builtin.group:
    name: docker
    state: present

- name: preconfig - Добавление пользователя в группу docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  register: user_add_result

- name: preconfig - Информирование о необходимости перезапуска сессии
  debug:
    # yamllint disable-line rule:line-length
    msg: "Пользователь {{ ansible_user }} добавлен в группу docker. Далее служба ssh будет перезапущена"
  when: user_add_result.changed
